name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node@18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: install
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GIT_HUB_APP_ID }}
          private_key: ${{ secrets.GIT_HUB_PRIVATE_KEY }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: pomodoro-timer
          directory: ./dist
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ steps.generate_token.outputs.token }}
